# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_env_vars(env_vars: 'AUTHKEY')
    app_store_connect_api_key(
      key_id: '52MJL54U87',
      issuer_id: 'c82e4c52-3c01-4bc3-ac1c-84a79e9f986a',
      key_content: ENV['AUTHKEY']
    )
    build_app(scheme: "Multiplayer Clock", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end
end
